version: '2'
services:
    salamtek-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/salamtek/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=salamtek
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
